package policy

import (
	"regexp"
	"strings"

	"github.com/amplify-lab/damping/core/event"
)

// matcher is the V1 hardcoded detection logic for one rule id. See
// docs/00-統一開發計畫（定案版）.md §四修正一 for why AST parsing alone
// (done upstream in cli/shell) does not remove the need for this explicit,
// testable, per-rule semantic layer — mvdan/sh gives structure, not intent.
type matcher func(Facts, Config) bool

// matchers is the V1 rule registry. Config.Validate rejects any configured
// rule id that has no entry here, so a typo in policy.yaml fails loudly at
// `damping doctor`/`damping policy validate` time instead of silently never
// firing.
var matchers = map[string]matcher{
	"destructive.rm_rf_protected":              matchRmRfProtected,
	"destructive.git_push_force":               matchGitPushForce,
	"destructive.sql_drop_truncate":            matchSQLDropTruncate,
	"destructive.chmod_777_recursive":          matchChmod777Recursive,
	"destructive.curl_pipe_sh_unallowlisted":   matchCurlPipeShUnallowlisted,
	"destructive.encoded_payload_pipe":         matchEncodedPayloadPipe,
	"destructive.proc_sandbox_bypass":          matchProcSandboxBypass,
	"destructive.dynamic_command_construction": matchDynamicCommandConstruction,
	"destructive.write_protected_path":         matchWriteProtectedPath,
	"mcp.write_tool_unscoped_identity":         matchMCPWriteToolUnscopedIdentity,
}

// RedirectWritePlaceholder is what cli/shell sets Facts.Command to when it
// finds an output redirection (>, >>, >|, &>, &>>) rather than a command
// invocation — e.g. "echo key >> ~/.ssh/authorized_keys" is dangerous
// because of the redirect target, not because "echo" itself is a risky
// command name.
const RedirectWritePlaceholder = "<redirect-write>"

func matchWriteProtectedPath(f Facts, cfg Config) bool {
	if f.Command != RedirectWritePlaceholder {
		return false
	}
	return inProtectedPaths(f.Target, cfg.ProtectedPaths)
}

// DynamicCommandPlaceholder is what cli/shell sets Facts.Command to when the
// command name itself could not be statically resolved to a literal (e.g.
// "$(echo rm) -rf ~/" — mvdan/sh's Word.Lit() returns "" for anything other
// than a plain literal). core/policy never assumes an unresolvable command
// name is safe merely because it can't prove otherwise — see
// features/dangerous_command.feature's "command constructed dynamically"
// scenario.
const DynamicCommandPlaceholder = "<dynamic>"

func matchDynamicCommandConstruction(f Facts, _ Config) bool {
	return f.Command == DynamicCommandPlaceholder
}

// regenerableDirNames are directories conventionally safe to `rm -rf` because
// they are regenerated by a build/package tool, not irreplaceable user data.
// This keeps the default policy from nagging on the single most common safe
// destructive-looking command developers run daily — see the "allow safe
// everyday commands" scenarios in features/dangerous_command.feature.
var regenerableDirNames = map[string]bool{
	"node_modules": true,
	"build":        true,
	"dist":         true,
	".next":        true,
	".cache":       true,
	"target":       true,
	"vendor":       true,
	"__pycache__":  true,
	".venv":        true,
	"venv":         true,
}

func matchRmRfProtected(f Facts, cfg Config) bool {
	if f.Command != "rm" {
		return false
	}
	if !hasRecursiveForce(f.Args) {
		return false
	}
	if isFilesystemOrHomeRoot(f.Target) {
		return true
	}
	if inProtectedPaths(f.Target, cfg.ProtectedPaths) {
		return true
	}
	return !regenerableDirNames[basename(f.Target)]
}

func matchGitPushForce(f Facts, _ Config) bool {
	if f.Command != "git" {
		return false
	}
	hasPush, hasForce := false, false
	for _, a := range f.Args {
		switch a {
		case "push":
			hasPush = true
		case "--force", "-f":
			hasForce = true
		}
	}
	return hasPush && hasForce
}

var sqlDestructivePattern = regexp.MustCompile(`(?i)\b(DROP\s+TABLE|TRUNCATE)\b`)

var sqlShellClients = map[string]bool{
	"psql":    true,
	"mysql":   true,
	"sqlite3": true,
	"mongosh": true,
}

func matchSQLDropTruncate(f Facts, _ Config) bool {
	if !sqlShellClients[f.Command] {
		return false
	}
	for _, a := range f.Args {
		if sqlDestructivePattern.MatchString(a) {
			return true
		}
	}
	return false
}

func matchChmod777Recursive(f Facts, _ Config) bool {
	if f.Command != "chmod" {
		return false
	}
	has777, hasRecursive := false, false
	for _, a := range f.Args {
		switch a {
		case "777":
			has777 = true
		case "-R", "--recursive":
			hasRecursive = true
		}
	}
	return has777 && hasRecursive
}

var fetchCommands = map[string]bool{"curl": true, "wget": true}
var shellSinks = map[string]bool{"sh": true, "bash": true, "zsh": true}

func matchCurlPipeShUnallowlisted(f Facts, cfg Config) bool {
	if !f.IsPipeline || len(f.PipelineCmds) < 2 {
		return false
	}
	first := f.PipelineCmds[0]
	last := f.PipelineCmds[len(f.PipelineCmds)-1]
	if !fetchCommands[first] || !shellSinks[last] {
		return false
	}
	return !domainAllowlisted(f.Domain, cfg.AllowlistedInstallDomains)
}

var decodeCommands = map[string]bool{"base64": true}
var shellOrEvalSinks = map[string]bool{"sh": true, "bash": true, "zsh": true, "eval": true, "source": true}

// matchEncodedPayloadPipe flags a pipeline that decodes data and feeds it
// into a shell, regardless of what the decoded payload actually contains —
// see docs/threat-model.md §3: a static parser cannot see through runtime
// data, so the structural shape itself is the signal.
func matchEncodedPayloadPipe(f Facts, _ Config) bool {
	if !f.IsPipeline {
		return false
	}
	hasDecode := false
	for i, c := range f.PipelineCmds {
		if decodeCommands[c] {
			hasDecode = true
		}
		if i == len(f.PipelineCmds)-1 && shellOrEvalSinks[c] {
			if hasDecode {
				return true
			}
		}
	}
	return false
}

// procBypassPaths are known sandbox-escape path literals. mvdan/sh's parser
// has no special awareness of these — they're just string literals to it —
// so this is an explicit, maintained list, not something AST parsing derives
// automatically. See docs/threat-model.md §3.
var procBypassPaths = []string{
	"/proc/self/root/",
	"/proc/self/exe",
}

func matchProcSandboxBypass(f Facts, _ Config) bool {
	for _, p := range procBypassPaths {
		if strings.Contains(f.Raw, p) {
			return true
		}
	}
	return false
}

func matchMCPWriteToolUnscopedIdentity(f Facts, _ Config) bool {
	if f.ActionType != event.ActionToolCall {
		return false
	}
	if !hasTag(f.ToolTags, "write") {
		return false
	}
	return !f.HasIdentity
}

// --- helpers ---

func hasRecursiveForce(args []string) bool {
	hasR, hasF := false, false
	for _, a := range args {
		switch a {
		case "-rf", "-fr":
			hasR, hasF = true, true
		case "-r", "-R", "--recursive":
			hasR = true
		case "-f", "--force":
			hasF = true
		}
	}
	return hasR && hasF
}

func isFilesystemOrHomeRoot(target string) bool {
	switch target {
	case "/", "~", "~/", "$HOME":
		return true
	}
	return false
}

func inProtectedPaths(target string, protected []string) bool {
	for _, p := range protected {
		trimmed := strings.TrimSuffix(p, "/")
		if target == trimmed || strings.HasPrefix(target, trimmed+"/") {
			return true
		}
	}
	return false
}

func basename(target string) string {
	trimmed := strings.TrimRight(target, "/")
	if idx := strings.LastIndex(trimmed, "/"); idx != -1 {
		return trimmed[idx+1:]
	}
	return trimmed
}

func domainAllowlisted(domain string, allow []string) bool {
	for _, d := range allow {
		if strings.EqualFold(domain, d) {
			return true
		}
	}
	return false
}

func hasTag(tags []string, tag string) bool {
	for _, t := range tags {
		if t == tag {
			return true
		}
	}
	return false
}

func matchesAnyPattern(patterns []string, f Facts) bool {
	for _, p := range patterns {
		if matchGlobPattern(p, f.Raw) {
			return true
		}
	}
	return false
}

// matchGlobPattern supports a trailing "*" as a prefix wildcard (e.g.
// "git status*"), which is the pattern vocabulary documented for the
// always-allow/always-deny prompt responses in docs/cli-reference.md §12.
func matchGlobPattern(pattern, s string) bool {
	if strings.HasSuffix(pattern, "*") {
		return strings.HasPrefix(s, strings.TrimSuffix(pattern, "*"))
	}
	return pattern == s
}
