package policy

import (
	"regexp"
	"strings"
)

// regenerableDirNames are directories conventionally safe to `rm -rf` because
// they are regenerated by a build/package tool, not irreplaceable user data.
// This keeps the default policy from nagging on the single most common safe
// destructive-looking command developers run daily — see the "allow safe
// everyday commands" scenarios in features/dangerous_command.feature.
var regenerableDirNames = map[string]bool{
	"node_modules": true,
	"build":        true,
	"dist":         true,
	".next":        true,
	".cache":       true,
	"target":       true,
	"vendor":       true,
	"__pycache__":  true,
	".venv":        true,
	"venv":         true,
}

func matchRmRfProtected(f Facts, cfg Config) bool {
	if f.Command != "rm" {
		return false
	}
	if !hasRecursiveForce(f.Args) {
		return false
	}
	if isFilesystemOrHomeRoot(f.Target) {
		return true
	}
	if inProtectedPaths(f.Target, cfg.ProtectedPaths) {
		return true
	}
	return !regenerableDirNames[basename(f.Target)]
}

func matchWriteProtectedPath(f Facts, cfg Config) bool {
	if f.Command != RedirectWritePlaceholder {
		return false
	}
	return inProtectedPaths(f.Target, cfg.ProtectedPaths)
}

func matchDynamicCommandConstruction(f Facts, _ Config) bool {
	return f.Command == DynamicCommandPlaceholder
}

func matchGitPushForce(f Facts, _ Config) bool {
	if f.Command != "git" {
		return false
	}
	hasPush, hasForce := false, false
	for _, a := range f.Args {
		switch a {
		case "push":
			hasPush = true
		case "--force", "-f":
			hasForce = true
		}
	}
	return hasPush && hasForce
}

var sqlDestructivePattern = regexp.MustCompile(`(?i)\b(DROP\s+TABLE|TRUNCATE)\b`)

var sqlShellClients = map[string]bool{
	"psql":    true,
	"mysql":   true,
	"sqlite3": true,
	"mongosh": true,
}

func matchSQLDropTruncate(f Facts, _ Config) bool {
	if !sqlShellClients[f.Command] {
		return false
	}
	for _, a := range f.Args {
		if sqlDestructivePattern.MatchString(a) {
			return true
		}
	}
	return false
}

func matchChmod777Recursive(f Facts, _ Config) bool {
	if f.Command != "chmod" {
		return false
	}
	has777, hasRecursive := false, false
	for _, a := range f.Args {
		switch a {
		case "777":
			has777 = true
		case "-R", "--recursive":
			hasRecursive = true
		}
	}
	return has777 && hasRecursive
}

var fetchCommands = map[string]bool{"curl": true, "wget": true}
var shellSinks = map[string]bool{"sh": true, "bash": true, "zsh": true}

func matchCurlPipeShUnallowlisted(f Facts, cfg Config) bool {
	if !f.IsPipeline || len(f.PipelineCmds) < 2 {
		return false
	}
	first := f.PipelineCmds[0]
	last := f.PipelineCmds[len(f.PipelineCmds)-1]
	if !fetchCommands[first] || !shellSinks[last] {
		return false
	}
	return !domainAllowlisted(f.Domain, cfg.AllowlistedInstallDomains)
}

var decodeCommands = map[string]bool{"base64": true}
var shellOrEvalSinks = map[string]bool{"sh": true, "bash": true, "zsh": true, "eval": true, "source": true}

// matchEncodedPayloadPipe flags a pipeline that decodes data and feeds it
// into a shell, regardless of what the decoded payload actually contains —
// see docs/threat-model.md §3: a static parser cannot see through runtime
// data, so the structural shape itself is the signal.
func matchEncodedPayloadPipe(f Facts, _ Config) bool {
	if !f.IsPipeline {
		return false
	}
	hasDecode := false
	for i, c := range f.PipelineCmds {
		if decodeCommands[c] {
			hasDecode = true
		}
		if i == len(f.PipelineCmds)-1 && shellOrEvalSinks[c] {
			if hasDecode {
				return true
			}
		}
	}
	return false
}

// procBypassPaths are known sandbox-escape path literals. mvdan/sh's parser
// has no special awareness of these — they're just string literals to it —
// so this is an explicit, maintained list, not something AST parsing derives
// automatically. See docs/threat-model.md §3.
var procBypassPaths = []string{
	"/proc/self/root/",
	"/proc/self/exe",
}

func matchProcSandboxBypass(f Facts, _ Config) bool {
	for _, p := range procBypassPaths {
		if strings.Contains(f.Raw, p) {
			return true
		}
	}
	return false
}

// --- shared shell-fact helpers ---

func hasRecursiveForce(args []string) bool {
	hasR, hasF := false, false
	for _, a := range args {
		switch a {
		case "-rf", "-fr":
			hasR, hasF = true, true
		case "-r", "-R", "--recursive":
			hasR = true
		case "-f", "--force":
			hasF = true
		}
	}
	return hasR && hasF
}

func isFilesystemOrHomeRoot(target string) bool {
	switch target {
	case "/", "~", "~/", "$HOME":
		return true
	}
	return false
}

func inProtectedPaths(target string, protected []string) bool {
	for _, p := range protected {
		trimmed := strings.TrimSuffix(p, "/")
		if target == trimmed || strings.HasPrefix(target, trimmed+"/") {
			return true
		}
	}
	return false
}

func basename(target string) string {
	trimmed := strings.TrimRight(target, "/")
	if idx := strings.LastIndex(trimmed, "/"); idx != -1 {
		return trimmed[idx+1:]
	}
	return trimmed
}

func domainAllowlisted(domain string, allow []string) bool {
	for _, d := range allow {
		if strings.EqualFold(domain, d) {
			return true
		}
	}
	return false
}
