package policy

import (
	"regexp"
	"strings"
)

// regenerableDirNames are directories conventionally safe to `rm -rf` because
// they are regenerated by a build/package tool, not irreplaceable user data.
// This keeps the default policy from nagging on the single most common safe
// destructive-looking command developers run daily — see the "allow safe
// everyday commands" scenarios in features/dangerous_command.feature.
var regenerableDirNames = map[string]bool{
	"node_modules": true,
	"build":        true,
	"dist":         true,
	".next":        true,
	".cache":       true,
	"target":       true,
	"vendor":       true,
	"__pycache__":  true,
	".venv":        true,
	"venv":         true,
}

func matchRmRfProtected(f Facts, cfg Config) bool {
	if f.Command != "rm" {
		return false
	}
	if !hasRecursiveForce(f.Args) {
		return false
	}
	// rm accepts multiple path operands in a single invocation
	// ("rm -rf /etc build"), and every one of them gets force-recursively
	// deleted — so each operand is checked independently rather than just
	// Facts.Target (which used to be nothing more than the *last* word,
	// missing a dangerous earlier operand entirely, and misfiring on a
	// trailing flag like "-v" when there was no operand after it). See
	// features/dangerous_command.feature, "rm -rf with multiple path
	// operands, only one of which is dangerous".
	for _, target := range rmPathOperands(f.Args) {
		if isFilesystemOrHomeRoot(target) {
			return true
		}
		if inProtectedPaths(target, cfg.ProtectedPaths) {
			return true
		}
		if regenerableDirNames[basename(target)] || isUnderTempRoot(target) {
			continue
		}
		return true
	}
	return false
}

// tempRootPrefixes are conventional Unix scratch-space roots the OS clears on
// its own schedule (reboot, tmpfs, systemd-tmpfiles) — a target under one of
// these is regenerable by construction, the same reasoning already applied
// to regenerableDirNames, regardless of what the leaf directory is named.
// Deliberately not os.TempDir() (which follows $TMPDIR at runtime): this
// must stay a fixed, environment-independent set so
// core/policy/opa_equivalence_test.go can keep asserting byte-for-byte
// identical behavior between this Go engine and policy.rego, neither of
// which should depend on ambient process environment.
var tempRootPrefixes = []string{"/tmp", "/var/tmp"}

func isUnderTempRoot(target string) bool {
	for _, root := range tempRootPrefixes {
		if target == root || strings.HasPrefix(target, root+"/") {
			return true
		}
	}
	return false
}

// rmPathOperands returns the non-flag path operands of an rm invocation —
// mirrored exactly in policy.rego's rm_path_operands/is_rm_flag so the two
// engines stay behaviorally identical (core/policy/opa_equivalence_test.go).
func rmPathOperands(args []string) []string {
	var out []string
	for _, a := range args {
		if strings.HasPrefix(a, "-") && a != "-" {
			continue
		}
		out = append(out, a)
	}
	return out
}

func matchWriteProtectedPath(f Facts, cfg Config) bool {
	if f.Command != RedirectWritePlaceholder {
		return false
	}
	return inProtectedPaths(f.Target, cfg.ProtectedPaths)
}

func matchDynamicCommandConstruction(f Facts, _ Config) bool {
	return f.Command == DynamicCommandPlaceholder
}

func matchGitPushForce(f Facts, _ Config) bool {
	if f.Command != "git" {
		return false
	}
	hasPush, hasForce := false, false
	for _, a := range f.Args {
		switch a {
		case "push":
			hasPush = true
		case "--force", "-f":
			hasForce = true
		}
	}
	return hasPush && hasForce
}

var sqlDestructivePattern = regexp.MustCompile(`(?i)\b(DROP\s+TABLE|TRUNCATE)\b`)

// mongoDestructivePattern matches destructive MongoDB shell (mongosh) JS
// operations. sqlDestructivePattern can never match these — mongosh was
// listed as a covered client, but it uses JS method-call syntax, not SQL
// keywords, so "DROP TABLE"/"TRUNCATE" never appears in real Mongo usage and
// this rule silently never fired for it in practice. dropDatabase() and
// <collection>.drop() are unconditionally destructive; deleteMany/remove are
// only flagged with an empty filter ({} or no argument at all), since a real
// filter is ordinary, common, safe usage.
var mongoDestructivePattern = regexp.MustCompile(`(?i)\bdb\.\w+\.drop\(\)|\bdb\.dropDatabase\(\)|\.(?:deleteMany|remove)\(\s*(?:\{\s*\})?\s*\)`)

var sqlShellClients = map[string]bool{
	"psql":    true,
	"mysql":   true,
	"sqlite3": true,
	"mongosh": true,
}

// sqlUnscopedUpdateDeletePattern/sqlWhereClausePattern/
// sqlAlwaysTrueWherePattern extend this rule (2026-07 coverage expansion
// research) to catch UPDATE/DELETE issued via a shell-invoked SQL client
// with no WHERE clause at all, or one that's always true ("WHERE 1"/"WHERE
// TRUE") — the exact shape of this project's own docs/threat-model.md
// grounding incident (Replit deleting a production database). MySQL's own
// client has shipped --safe-updates/-U specifically to guard against this
// for 25+ years — independent, long-standing evidence this is a real risk
// category, not a novel concern invented for this rule.
var sqlUnscopedUpdateDeletePattern = regexp.MustCompile(`(?i)\b(UPDATE\s+\S+\s+SET\b|DELETE\s+FROM\b)`)
var sqlWhereClausePattern = regexp.MustCompile(`(?i)\bWHERE\b`)
var sqlAlwaysTrueWherePattern = regexp.MustCompile(`(?i)\bWHERE\s+(1|TRUE)\s*;?\s*$`)

// redisShellClients/redisFlushPattern extend the same rule id to
// redis-cli's FLUSHALL/FLUSHDB — the identical "wipe everything, no
// per-row scoping possible" shape as SQL TRUNCATE, just a different
// client, so this stays part of destructive.sql_drop_truncate rather than
// becoming its own rule id.
var redisShellClients = map[string]bool{"redis-cli": true}
var redisFlushPattern = regexp.MustCompile(`(?i)^(FLUSHALL|FLUSHDB)$`)

func matchSQLDropTruncate(f Facts, _ Config) bool {
	if redisShellClients[f.Command] {
		for _, a := range f.Args {
			if redisFlushPattern.MatchString(a) {
				return true
			}
		}
		return false
	}
	if !sqlShellClients[f.Command] {
		return false
	}
	for _, a := range f.Args {
		if sqlDestructivePattern.MatchString(a) {
			return true
		}
		if f.Command == "mongosh" && mongoDestructivePattern.MatchString(a) {
			return true
		}
		if hasUnscopedUpdateOrDelete(a) {
			return true
		}
	}
	return false
}

// hasUnscopedUpdateOrDelete reports whether a contains an UPDATE...SET or
// DELETE FROM statement with no WHERE clause, or one that's always true.
// Known, accepted false-negative for v1: a WHERE clause containing a
// subquery that's itself unscoped (e.g. "WHERE id IN (SELECT id FROM t)")
// reads as "has a WHERE" to this text-level check even if that subquery is
// itself dangerous — catching that would need real SQL parsing, a
// different order of engineering than this project's existing regex-level
// SQL matching.
func hasUnscopedUpdateOrDelete(a string) bool {
	if !sqlUnscopedUpdateDeletePattern.MatchString(a) {
		return false
	}
	if !sqlWhereClausePattern.MatchString(a) {
		return true
	}
	return sqlAlwaysTrueWherePattern.MatchString(a)
}

func matchChmod777Recursive(f Facts, _ Config) bool {
	if f.Command != "chmod" {
		return false
	}
	has777, hasRecursive := false, false
	for _, a := range f.Args {
		if isWorldWritableOctalMode(a) {
			has777 = true
		}
		switch {
		case a == "--recursive":
			hasRecursive = true
		case isShortFlagCluster(a):
			// chmod's short recursive flag is uppercase-only (-R); unlike
			// rm, lowercase -r is not a valid chmod flag at all, so only R
			// counts here — see hasRecursiveForce for the rm/rf case, which
			// does accept either case.
			for _, ch := range a[1:] {
				if ch == 'R' {
					hasRecursive = true
				}
			}
		}
	}
	return has777 && hasRecursive
}

// isWorldWritableOctalMode matches any all-octal-digit mode string ending in
// 777 (777, 0777, 1777 with the sticky bit, 2777, ...) — a leading digit or
// leading zeros don't change that the low three bits grant world write.
func isWorldWritableOctalMode(a string) bool {
	if a == "" {
		return false
	}
	for _, c := range a {
		if c < '0' || c > '7' {
			return false
		}
	}
	return strings.HasSuffix(a, "777")
}

var fetchCommands = map[string]bool{"curl": true, "wget": true}
var shellSinks = map[string]bool{"sh": true, "bash": true, "zsh": true}

func matchCurlPipeShUnallowlisted(f Facts, cfg Config) bool {
	if !f.IsPipeline || len(f.PipelineCmds) < 2 {
		return false
	}
	first := f.PipelineCmds[0]
	last := f.PipelineCmds[len(f.PipelineCmds)-1]
	if !fetchCommands[first] || !shellSinks[last] {
		return false
	}
	return !domainAllowlisted(f.Domain, cfg.AllowlistedInstallDomains)
}

// decodeCommands are decode primitives whose bare command name is
// unambiguous — the binary's only real-world purpose is decoding, unlike
// xxd (also used for plain hex dumps) or openssl (dozens of unrelated
// subcommands), which are matched separately via decodeFlagPatterns below
// since PipelineCmds only carries command names, not their arguments.
var decodeCommands = map[string]bool{"base64": true, "base32": true, "uudecode": true}
var shellOrEvalSinks = map[string]bool{"sh": true, "bash": true, "zsh": true, "eval": true, "source": true}

// decodeFlagPatterns catches decode primitives whose command name alone
// doesn't tell you whether the call decodes anything — checked against the
// raw command text directly (PipelineCmds has no per-stage args to inspect),
// the same "AST position can't see this, so match the textual signal
// instead" approach matchProcSandboxBypass already uses for /proc paths.
var decodeFlagPatterns = []*regexp.Regexp{
	regexp.MustCompile(`\bxxd\s+(?:-\S+\s+)*-r\b`),             // xxd -r / xxd -r -p (hex decode; bare xxd only hex-dumps)
	regexp.MustCompile(`\bopenssl\s+(?:enc|base64)\b.*\s-d\b`), // openssl enc -d / openssl base64 -d
}

func hasDecodeFlagPattern(raw string) bool {
	for _, p := range decodeFlagPatterns {
		if p.MatchString(raw) {
			return true
		}
	}
	return false
}

// matchEncodedPayloadPipe flags a pipeline that decodes data and feeds it
// into a shell, regardless of what the decoded payload actually contains —
// see docs/threat-model.md §3: a static parser cannot see through runtime
// data, so the structural shape itself is the signal.
func matchEncodedPayloadPipe(f Facts, _ Config) bool {
	if !f.IsPipeline {
		return false
	}
	hasDecode := hasDecodeFlagPattern(f.Raw)
	for i, c := range f.PipelineCmds {
		if decodeCommands[c] {
			hasDecode = true
		}
		if i == len(f.PipelineCmds)-1 && shellOrEvalSinks[c] {
			if hasDecode {
				return true
			}
		}
	}
	return false
}

// procBypassPaths are known sandbox-escape path literals. mvdan/sh's parser
// has no special awareness of these — they're just string literals to it —
// so this is an explicit, maintained list, not something AST parsing derives
// automatically. See docs/threat-model.md §3.
var procBypassPaths = []string{
	"/proc/self/root/",
	"/proc/self/exe",
}

func matchProcSandboxBypass(f Facts, _ Config) bool {
	for _, p := range procBypassPaths {
		if strings.Contains(f.Raw, p) {
			return true
		}
	}
	return false
}

// --- shared shell-fact helpers ---

// hasRecursiveForce recognizes GNU rm's recursive+force flags in any of
// their real forms: the long flags, the plain short flags, and any combined
// short-flag cluster in either order and either case for the recursive
// letter — "-rf", "-fr", "-Rf", "-fR" are all real, common spellings of
// "recursive and force" and must all be caught. This was a real bypass: an
// earlier version only matched the literal strings "-rf"/"-fr", so
// "rm -Rf /" (a very common way to type this) slipped through
// destructive.rm_rf_protected entirely — see core/policy/rules_shell_test.go.
func hasRecursiveForce(args []string) bool {
	hasR, hasF := false, false
	for _, a := range args {
		switch {
		case a == "--recursive":
			hasR = true
		case a == "--force":
			hasF = true
		case isShortFlagCluster(a):
			for _, ch := range a[1:] {
				switch ch {
				case 'r', 'R':
					hasR = true
				case 'f':
					hasF = true
				}
			}
		}
	}
	return hasR && hasF
}

// isShortFlagCluster reports whether a is a POSIX short-option cluster like
// "-rf" or "-Rfv" — a single dash followed by one or more option letters,
// as opposed to a long option ("--force") or a bare "-" or "--".
func isShortFlagCluster(a string) bool {
	return len(a) > 1 && a[0] == '-' && a[1] != '-'
}

func isFilesystemOrHomeRoot(target string) bool {
	switch target {
	case "/", "~", "~/", "$HOME":
		return true
	}
	return false
}

func inProtectedPaths(target string, protected []string) bool {
	for _, p := range protected {
		trimmed := strings.TrimSuffix(p, "/")
		if target == trimmed || strings.HasPrefix(target, trimmed+"/") {
			return true
		}
	}
	return false
}

func basename(target string) string {
	trimmed := strings.TrimRight(target, "/")
	if idx := strings.LastIndex(trimmed, "/"); idx != -1 {
		return trimmed[idx+1:]
	}
	return trimmed
}

func domainAllowlisted(domain string, allow []string) bool {
	for _, d := range allow {
		if strings.EqualFold(domain, d) {
			return true
		}
	}
	return false
}
