@phase4
Feature: Team audit dashboard (Phase 4 — not implemented in V1)
  As a team lead using Damping Team
  I want visibility into my team's agent activity across members
  So that I can see risky patterns without any member's data leaking without consent

  Background:
    Given the team has a Damping Team workspace on Cloudflare (Track A)

  Scenario: A team member's interception appears in the live stream
    Given team member "alice" has opted in via "damping sync enable"
    When alice's agent is intercepted attempting "rm -rf ~/"
    Then the team dashboard should show the event in the real-time stream within a few seconds
    And the event should include channel, risk level, and decision

  Scenario: A non-opted-in member's data never appears
    Given team member "bob" has not run "damping sync enable"
    When bob's agent is intercepted attempting a destructive command
    Then no data about that event should appear anywhere in the team dashboard

  Scenario: Policy can be pushed to all team members from the dashboard
    Given the team lead edits the shared policy in the dashboard
    When the change is published
    Then all opted-in members' local Damping installs should receive the updated policy
    And each member's local audit log should continue to be the local source of truth for their own machine

  Scenario: A storage backend failure degrades gracefully
    Given the Durable Object handling the team's live stream is temporarily unavailable
    When new events are generated by team members
    Then the dashboard should show a clear "reconnecting" state instead of silently losing events
    And the dashboard should offer a manual reset/retry action

  Scenario: Alerting on repeated high-risk interceptions
    Given a team member's agent has been denied 5 or more high-risk actions in the last hour
    When this threshold is crossed
    Then a Slack alert should be sent to the configured channel
    And the alert should link directly to the relevant events in the dashboard
